#!/bin/tcsh -f
#
# You may copy this file for other functions
#
cat reverse_prefix_sum.s reverse_prefix_sum_driver.s > reverse_prefix_sum_prog.s
spim -file reverse_prefix_sum_prog.s | tail -n +2
rm -f reverse_prefix_sum_prog.s
# "tail -n+2" strips the first line of spim's output, which is irrelevant