#!/bin/tcsh -f
#
# You may copy this file for other functions
#
cat isqrt.s isqrt_driver.s > isqrt_prog.s
spim -file isqrt_prog.s | tail -n +2
rm -f isqrt_prog.s
# "tail -n+2" strips the first line of spim's output, which is irrelevant